### ISSUE TITLE
The app cannot connect to the server

### ISSUE THREAD

**Issue by MrZJ** [razaghimahdi/Shopping-By-KMP#32]

**Comment by razaghimahdi** [comment]
Yeah, the entire server has been down for the past couple of weeks. I'm still working on it and will get it fixed as soon as possible.

**Comment by razaghimahdi** [comment]
But u can still run app locally if you get clone from backend project

**Comment by vzhilong** [comment]
It server up now?

**Comment by razaghimahdi** [comment]
@vzhilong it will fixed in next couple days, meanwhile you can run app locally just clone the backend(Php or Ktor)

**Comment by ercanduman** [comment]
Does the issue still persist? We are still unable to log in, sign up, or access the app.

**Comment by razaghimahdi** [comment]
Hi there, it's been 2 weeks that we fixed server. So to make sure app works, make a clone from project and run it. thanks for your patience
